export const GET_AUTHORS = 'GET_AUTHORS';
export const CREATE_AUTHORS = 'CREATE_AUTHORS';
export const UPDATE_AUTHORS = 'UPDATE_AUTHORS';
export const DELETE_AUTHORS = 'DELETE_AUTHORS';
export const SET_LOADED_AUTHORS = 'SET_LOADED_AUTHORS';
export const SET_PAGE_AUTHORS = 'SET_PAGE_AUTHORS';